#!/bin/bash -l
#SBATCH --job-name="HPC"
#SBATCH --account="uzh8"
#SBATCH --time=00:05:00
#SBATCH --nodes=2
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=36
#SBATCH --partition=debug
#SBATCH --constraint=mc
#SBATCH --hint=nomultithread
#SBATCH --error=error.log
#SBATCH --output=output.log

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun ./cpi_omp
